# This is a config for E2B sandbox template.
# You can use template ID (sd78l4j5g5h5wghecw4l) or template name (wzero-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("wzero-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("wzero-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('wzero-nextjs-test-2')

team_id = "72de489b-53a9-45de-b85f-2d8240d17639"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "wzero-nextjs-test-2"
template_id = "sd78l4j5g5h5wghecw4l"
